# Generated by Django 4.2.10 on 2026-04-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('futsals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='futsals.timeslot'),
        ),
    ]
