# Generated by Django 4.2.10 on 2026-04-03 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('futsals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futsals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['futsal', 'slot_date'], name='futsals_tim_futsal__61a0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['availability_status'], name='futsals_tim_availab_e10f96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('futsal', 'slot_date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='futsal',
            index=models.Index(fields=['owner'], name='futsals_fut_owner_i_b64285_idx'),
        ),
        migrations.AddIndex(
            model_name='futsal',
            index=models.Index(fields=['approval_status'], name='futsals_fut_approva_b1cf7a_idx'),
        ),
    ]
