# Generated by Django 4.2.10 on 2026-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='futsal_images/'),
        ),
    ]
