# Generated by Django 4.2.10 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futsals", "0005_alter_timeslot_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="futsal",
            name="esewa_qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="payment_qr/esewa/"),
        ),
        migrations.AddField(
            model_name="futsal",
            name="fonepay_qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="payment_qr/fonepay/"),
        ),
        migrations.AddField(
            model_name="futsal",
            name="preferred_qr_provider",
            field=models.CharField(
                choices=[("esewa", "eSewa"), ("fonepay", "Fonepay")],
                default="esewa",
                max_length=20,
            ),
        ),
    ]
