# Generated by Django 4.2.10 on 2026-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('alert', 'Alert'), ('review', 'Review'), ('opponent', 'Opponent'), ('system', 'System')], max_length=20),
        ),
    ]
