# Generated by Django 4.2.10 on 2026-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proof/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('cash', 'Cash'), ('e_wallet', 'E-Wallet')], max_length=20),
        ),
    ]
